global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'concrnt'
    static_configs:
      - targets:
        - 'concrnt:8000'
        - 'postgres-exporter:9187'
        - 'redis-exporter:9121'
        - 'memcached-exporter:9150'
        labels:
          instance: concrnt-local
